# Generated by Django 6.1 on 2026-09-11 15:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_table_qr_code'),
        ('staff', '0002_shift_employeeprofile_shift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('grace_minutes', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(120)])),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='staff.employeeprofile')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_attendance', to='restaurant.restaurant')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='staff.shift')),
            ],
            options={
                'ordering': ['-work_date', '-check_in'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'work_date'), name='staff_one_attendance_per_work_date'), models.UniqueConstraint(condition=models.Q(('check_out__isnull', True)), fields=('employee',), name='staff_one_open_attendance_per_employee'), models.CheckConstraint(condition=models.Q(('scheduled_end__gt', models.F('scheduled_start'))), name='staff_attendance_schedule_valid'), models.CheckConstraint(condition=models.Q(('check_out__isnull', True), ('check_out__gte', models.F('check_in')), _connector='OR'), name='staff_attendance_checkout_valid'), models.CheckConstraint(condition=models.Q(('grace_minutes__lte', 120)), name='staff_attendance_grace_max_120')],
            },
        ),
    ]
