# Generated by Django 6.1 on 2026-09-17 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_discount_amount_order_payment_method_and_more'),
        ('restaurant', '0002_table_qr_code'),
        ('staff', '0005_payrollrecord_salaryadvance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTableAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_daily_tables', to=settings.AUTH_USER_MODEL)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_assignments', to='staff.attendance')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_table_assignments', to='restaurant.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_waiter_assignments', to='restaurant.table')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_table_assignments', to='staff.employeeprofile')),
            ],
            options={
                'ordering': ['-work_date', 'table__table_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderStaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_service', to='orders.order')),
                ('table_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_services', to='staff.dailytableassignment')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='served_order_records', to='staff.employeeprofile')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_order', 'New Order'), ('food_ready', 'Food Ready'), ('order_served', 'Order Served'), ('order_completed', 'Order Completed'), ('task_assigned', 'Task Assigned'), ('general', 'General')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('event_key', models.CharField(help_text='Stable event identifier used to prevent duplicate notifications.', max_length=180)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_notifications', to='orders.order')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notifications', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notifications', to='restaurant.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_staff_tasks', to=settings.AUTH_USER_MODEL)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to='staff.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to='staff.employeeprofile')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_tasks', to='orders.order')),
                ('related_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_tasks', to='restaurant.table')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_tasks', to='restaurant.restaurant')),
            ],
            options={
                'ordering': ['is_completed', '-assigned_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailytableassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('table', 'work_date'), name='staff_one_waiter_per_table_day'),
        ),
        migrations.AddIndex(
            model_name='staffnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='staff_notif_user_read_idx'),
        ),
        migrations.AddIndex(
            model_name='staffnotification',
            index=models.Index(fields=['order'], name='staff_notif_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffnotification',
            constraint=models.UniqueConstraint(fields=('recipient', 'event_key'), name='staff_unique_recipient_event'),
        ),
        migrations.AddIndex(
            model_name='stafftask',
            index=models.Index(fields=['restaurant', 'work_date', 'is_completed'], name='staff_task_daily_idx'),
        ),
    ]
