# Generated by Django 6.1 on 2026-09-18 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_dailytableassignment_orderstaffservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryadvance',
            name='payroll_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_advances', to='staff.payrollrecord'),
        ),
    ]
