# Generated by Django 6.1 on 2026-09-20 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_branch_remove_floor_unique_floor_name_per_restaurant_and_more'),
        ('staff', '0007_salaryadvance_payroll_record'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shift',
            name='staff_unique_shift_name_per_restaurant',
        ),
        migrations.AddField(
            model_name='attendance',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance', to='restaurant.branch'),
        ),
        migrations.AddField(
            model_name='dailytableassignment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_table_assignments', to='restaurant.branch'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_leave_requests', to='restaurant.branch'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_payroll_records', to='restaurant.branch'),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_salary_advances', to='restaurant.branch'),
        ),
        migrations.AddField(
            model_name='shift',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_shifts', to='restaurant.branch'),
        ),
        migrations.AddField(
            model_name='staffnotification',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_notifications', to='restaurant.branch'),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_tasks', to='restaurant.branch'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='staff_unique_shift_name_per_branch'),
        ),
    ]
