# Generated by Django 6.1 on 2026-09-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_remove_shift_staff_unique_shift_name_per_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstaffservice',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
