# Generated by Django 6.1 on 2026-09-21 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_orderstaffservice_ready_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstaffservice',
            name='closed_by',
            field=models.ForeignKey(blank=True, help_text='User who closed or cleaned the table service.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_order_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstaffservice',
            name='handover_by',
            field=models.ForeignKey(blank=True, help_text='Previous waiter if service was handed over.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_from_services', to='staff.employeeprofile'),
        ),
        migrations.AddField(
            model_name='orderstaffservice',
            name='order_taken_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who took/entered the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_taken_services', to='staff.employeeprofile'),
        ),
        migrations.AddField(
            model_name='orderstaffservice',
            name='payment_handled_by',
            field=models.ForeignKey(blank=True, help_text='User who processed or recorded payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_handled_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstaffservice',
            name='served_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who marked the order as served.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_served_services', to='staff.employeeprofile'),
        ),
    ]
