from django.urls import path

from . import operations_views, views


app_name = "staff"

urlpatterns = [
    path(
        "operations/",
        operations_views.daily_operations,
        name="daily_operations",
    ),
    path(
        "operations/tables/assign/",
        operations_views.daily_table_assign,
        name="daily_table_assign",
    ),
    path(
        "operations/tasks/assign/",
        operations_views.daily_task_assign,
        name="daily_task_assign",
    ),
    path(
        "operations/tasks/<int:task_id>/complete/",
        operations_views.daily_task_complete,
        name="daily_task_complete",
    ),
    path(
        "operations/orders/<int:order_id>/serve/",
        operations_views.waiter_serve_order,
        name="waiter_serve_order",
    ),
    path(
        "employees/",
        views.employee_list,
        name="employee_list",
    ),
    path(
        "employees/add/",
        views.employee_create,
        name="employee_create",
    ),

        path(
        "employees/<int:employee_id>/",
        views.employee_detail,
        name="employee_detail",
    ),

    path(
        "employees/<int:employee_id>/edit/",
        views.employee_edit,
        name="employee_edit",
    ),
    path(
        "employees/<int:employee_id>/status/",
        views.employee_set_status,
        name="employee_set_status",
    ),
    path(
        "employees/<int:employee_id>/shift/",
        views.employee_assign_shift,
        name="employee_assign_shift",
    ),
    path(
        "shifts/",
        views.shift_list,
        name="shift_list",
    ),
    path(
        "shifts/add/",
        views.shift_create,
        name="shift_create",
    ),
    path(
        "shifts/<int:shift_id>/edit/",
        views.shift_edit,
        name="shift_edit",
    ),
    path(
        "shifts/<int:shift_id>/status/",
        views.shift_set_status,
        name="shift_set_status",
    ),
    path(
        "salary-advances/",
        views.salary_advance_list,
        name="salary_advance_list",
    ),
    path(
        "salary-advances/<int:advance_id>/review/",
        views.salary_advance_review,
        name="salary_advance_review",
    ),
    path(
        "payroll/",
        views.payroll_list,
        name="payroll_list",
    ),
    path(
        "payroll/<int:payroll_id>/paid/",
        views.payroll_mark_paid,
        name="payroll_mark_paid",
    ),
    path(
        "leave/create-for-staff/",
        views.staff_leave_create,
        name="staff_leave_create",
    ),
    path(
        "leave/",
        views.leave_list,
        name="leave_list",
    ),
    path(
        "leave/<int:leave_id>/review/",
        views.leave_review,
        name="leave_review",
    ),
    path(
        "leave/my/",
        views.my_leave,
        name="my_leave",
    ),
    path(
        "attendance/export/",
        views.attendance_export_csv,
        name="attendance_export_csv",
    ),
    path(
        "attendance/",
        views.attendance_list,
        name="attendance_list",
    ),
    path(
        "attendance/my/",
        views.my_attendance,
        name="my_attendance",
    ),
    path(
        "attendance/action/",
        views.attendance_action,
        name="attendance_action",
    ),
]