# Generated by Django 6.1 on 2026-09-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='is_customer_visible',
            field=models.BooleanField(default=False, help_text='Show this ingredient name to customers on the menu item details page.'),
        ),
    ]
