# Generated by Django 6.1 on 2026-09-18 21:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_supplier_purchaseorder_purchaseorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='unit_cost_snapshot',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
    ]
