# Generated by Django 6.1 on 2026-09-20 14:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stocktransaction_unit_cost_snapshot'),
        ('restaurant', '0004_alter_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('OPENING_BALANCE', 'Opening Balance'), ('PURCHASE', 'Purchase'), ('CONSUMPTION', 'Order Consumption'), ('WASTE', 'Waste'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('RETURN', 'Return')], max_length=30),
        ),
    ]
