# Generated by Django 6.1 on 2026-09-20 15:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_backfill_opening_stock_transactions'),
        ('menu', '0003_addongroup_addonoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonOptionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('addon_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_requirements', to='menu.addonoption')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addon_usages', to='inventory.ingredient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('addon_option', 'ingredient'), name='unique_ingredient_per_addon_option')],
            },
        ),
    ]
