# Generated by Django 6.1 on 2026-09-20 16:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_addonoptioningredient'),
        ('restaurant', '0005_branch_remove_floor_unique_floor_name_per_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='restaurant.branch'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='restaurant.branch'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='restaurant.branch'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='restaurant.branch'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='restaurant.branch'),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='restaurant.branch'),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='restaurant.restaurant'),
        ),
        migrations.CreateModel(
            name='BranchIngredientStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('reserved_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('min_stock_alert', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_stocks', to='restaurant.branch')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='inventory.ingredient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('branch', 'ingredient'), name='unique_branch_ingredient_stock')],
            },
        ),
    ]
