"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file if available
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env")
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    os.environ.get(
        "SECRET_KEY",
        "django-insecure-u60hq_%9s1p)6#mtpbad++o0d_%nhb1eelfkhky0j6mb$gb#6&",
    ),
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get(
    "DJANGO_DEBUG",
    os.environ.get("DEBUG", "True"),
).lower() in ("true", "1", "yes")


from urllib.parse import urlsplit


def _normalize_origin_candidates(val: str) -> list[str]:
    val = (val or "").strip().rstrip("/")
    if not val:
        return []
    candidates = []
    parts = [p.strip() for p in val.split(",") if p.strip()]
    for part in parts:
        if part.startswith(("http://", "https://")):
            parsed = urlsplit(part)
            if parsed.netloc:
                candidates.append(f"{parsed.scheme}://{parsed.netloc}")
                alt_scheme = "https" if parsed.scheme == "http" else "http"
                candidates.append(f"{alt_scheme}://{parsed.netloc}")
        else:
            candidates.append(f"http://{part}")
            candidates.append(f"https://{part}")
    return candidates


def _normalize_origin(val: str) -> str:
    cands = _normalize_origin_candidates(val)
    return cands[0] if cands else ""


_allowed_hosts = os.environ.get(
    "DJANGO_ALLOWED_HOSTS",
    os.environ.get("ALLOWED_HOSTS", ""),
)
if _allowed_hosts:
    ALLOWED_HOSTS = [h.strip().lower() for h in _allowed_hosts.split(",") if h.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = [
        "127.0.0.1",
        "localhost",
        "testserver",
    ]

# Public, phone-reachable origin. Never infer this from container/network interfaces.
SITE_URL = os.environ.get("SITE_URL", "").strip().rstrip("/")

if SITE_URL:
    _site_parsed = urlsplit(SITE_URL if SITE_URL.startswith(("http://", "https://")) else f"http://{SITE_URL}")
    if _site_parsed.hostname and _site_parsed.hostname.lower() not in ALLOWED_HOSTS and "*" not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_site_parsed.hostname.lower())

# CSRF trusted origins: configured from env and SITE_URL; never disable CSRF.
CSRF_TRUSTED_ORIGINS = []
_csrf_origins = os.environ.get(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    os.environ.get("CSRF_TRUSTED_ORIGINS", ""),
)
if _csrf_origins:
    for cand in _normalize_origin_candidates(_csrf_origins):
        if cand not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(cand)

if SITE_URL:
    for cand in _normalize_origin_candidates(SITE_URL):
        if cand not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(cand)

if _allowed_hosts:
    site_port = ""
    if SITE_URL:
        _sp = urlsplit(SITE_URL if SITE_URL.startswith(("http://", "https://")) else f"http://{SITE_URL}")
        if _sp.port:
            site_port = f":{_sp.port}"
    for host in _allowed_hosts.split(","):
        host = host.strip()
        if not host or host == "*" or host.startswith("."):
            continue
        if ":" in host:
            for cand in _normalize_origin_candidates(host):
                if cand not in CSRF_TRUSTED_ORIGINS:
                    CSRF_TRUSTED_ORIGINS.append(cand)
        else:
            for cand in _normalize_origin_candidates(host):
                if cand not in CSRF_TRUSTED_ORIGINS:
                    CSRF_TRUSTED_ORIGINS.append(cand)
            if site_port:
                for cand in _normalize_origin_candidates(f"{host}{site_port}"):
                    if cand not in CSRF_TRUSTED_ORIGINS:
                        CSRF_TRUSTED_ORIGINS.append(cand)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'restaurant',
    'menu',
    'orders',
    'kitchen',
    'dashboard',
    'inventory',
    'pos',
    'staff.apps.StaffConfig',
    'finance',
    'guests',
    'business_settings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'restaurant.context_processors.active_branch_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': BASE_DIR / os.environ.get('DB_NAME', 'db.sqlite3'),
        # SQLite has no row-level SELECT FOR UPDATE. Acquire its write lock at
        # the start of atomic blocks so stock checks cannot race reservations.
        'OPTIONS': {
            'transaction_mode': 'IMMEDIATE',
            'timeout': 20,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = os.environ.get('STATIC_URL', '/static/')
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads, QR codes, menu photos)
MEDIA_URL = os.environ.get('MEDIA_URL', '/media/')
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Login URL
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'users:role_dashboard'
LOGOUT_REDIRECT_URL = 'users:login'

# Messages
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}
