# Generated by Django 6.1 on 2026-09-20 18:26

import django.core.validators
import django.db.models.deletion
import guests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0010_order_branch_paymenttransaction_branch_and_more'),
        ('restaurant', '0006_backfill_main_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=guests.models.feedback_token, editable=False, max_length=43, unique=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_feedback', to='orders.order')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='feedback_rating_range')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('party_size', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('note', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.branch')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'ordering': ['date', 'time', 'pk'],
                'indexes': [models.Index(fields=['restaurant', 'branch', 'date'], name='guests_rese_restaur_2073bf_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('party_size__gte', 1)), name='reservation_positive_party_size')],
            },
        ),
    ]
