# Generated by Django 6.1 on 2026-09-17 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_table_qr_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['floor__floor_number', 'table_number']},
        ),
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('WAITING', 'Waiting'), ('SERVING', 'Serving'), ('CLEANING', 'Cleaning'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor_number', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='restaurant.restaurant')),
            ],
            options={
                'ordering': ['floor_number', 'name'],
            },
        ),
        migrations.AddField(
            model_name='table',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='restaurant.floor'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('restaurant', 'table_number'), name='unique_table_number_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_floor_name_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('restaurant', 'floor_number'), name='unique_floor_number_per_restaurant'),
        ),
    ]
