# Generated by Django 6.1 on 2026-09-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_table_options_table_capacity_table_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('WAITING', 'Waiting'), ('SERVING', 'Serving'), ('CLEANING', 'Cleaning'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20),
        ),
    ]
