# Generated by Django 6.1 on 2026-09-10 07:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(choices=[('NORMAL', 'Normal Food'), ('SET_MENU', 'Set Menu')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='serves',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of people this item normally serves.'),
        ),
        migrations.CreateModel(
            name='SetMenuComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantity/portion of this food included in the set menu.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='included_in_sets', to='menu.menuitem')),
                ('set_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_components', to='menu.menuitem')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('set_menu', 'component'), name='unique_component_per_set_menu')],
            },
        ),
    ]
