# Generated by Django 6.1 on 2026-09-20 15:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_item_type_menuitem_serves_setmenucomponent'),
        ('restaurant', '0004_alter_table_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('selection_type', models.CharField(choices=[('SINGLE', 'Single Selection (Choose One)'), ('MULTIPLE', 'Multiple Selection (Choose Many)')], default='SINGLE', max_length=20)),
                ('is_required', models.BooleanField(default=False, help_text='Whether customer must make a selection from this group.')),
                ('min_selection', models.PositiveSmallIntegerField(default=0, help_text='Minimum options required to select.')),
                ('max_selection', models.PositiveSmallIntegerField(blank=True, help_text='Maximum options allowed to select (blank for unlimited in multiple).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_items', models.ManyToManyField(blank=True, related_name='addon_groups', to='menu.menuitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_groups', to='restaurant.restaurant')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AddonOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra price for this option (0 for free).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.addongroup')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
