# Generated by Django 6.1 on 2026-09-20 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_addongroup_addonoption'),
        ('restaurant', '0005_branch_remove_floor_unique_floor_name_per_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMenuItemOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, help_text='Branch-specific item availability.')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional branch-specific price override.', max_digits=10, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_overrides', to='restaurant.branch')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_overrides', to='menu.menuitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('branch', 'menu_item'), name='unique_branch_menu_item_override')],
            },
        ),
    ]
