# Generated by Django 6.1 on 2026-09-18 12:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_table_sessions(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    TableSession = apps.get_model('orders', 'TableSession')

    dine_in_orders = Order.objects.filter(order_type='DINE_IN', table__isnull=False).order_by('created_at')
    sessions_by_key = {}
    for order in dine_in_orders:
        table_id = order.table_id
        is_completed = order.status in ('COMPLETED', 'CANCELLED')
        date_key = order.created_at.date() if order.created_at else 'unknown'
        key = (table_id, date_key, is_completed)
        session = sessions_by_key.get(key)
        if not session:
            session = TableSession.objects.create(
                restaurant_id=order.restaurant_id,
                table_id=table_id,
                status='CLOSED' if is_completed else 'OPEN',
                opened_at=order.created_at or django.utils.timezone.now(),
                closed_at=order.created_at if is_completed else None,
            )
            sessions_by_key[key] = session
        order.table_session = session
        order.save(update_fields=['table_session'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_reference'),
        ('restaurant', '0004_alter_table_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_sessions', to='restaurant.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='restaurant.table')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.tablesession'),
        ),
        migrations.RunPython(backfill_table_sessions, migrations.RunPython.noop),
    ]
