# Generated by Django 6.1 on 2026-09-20 15:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_addongroup_addonoption'),
        ('orders', '0007_order_paid_at_order_refund_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_group_name', models.CharField(blank=True, default='', max_length=120)),
                ('addon_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addon_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_addons', to='menu.addonoption')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='orders.orderitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
