# Generated by Django 6.1 on 2026-09-20 16:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_addongroup_addonoption'),
        ('orders', '0008_orderitemaddon'),
        ('restaurant', '0004_alter_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_type_snapshot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, db_index=True, default='', help_text='Coupon code (case-insensitive). Leave blank for automatic offers.', max_length=50)),
                ('is_automatic', models.BooleanField(db_index=True, default=False, help_text='Automatically applied to qualifying orders if no coupon code is specified.')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount (৳)')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage value (e.g. 10.00 for 10%) or Fixed amount (e.g. 50.00 for ৳50).', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount cap for percentage offers (null for uncapped).', max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum eligible subtotal required to use this coupon.', max_digits=10)),
                ('start_datetime', models.DateTimeField(blank=True, help_text='Optional start date/time when coupon becomes active.', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, help_text='Optional expiry date/time after which coupon cannot be used.', null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum total times this coupon can be used across all orders (null for unlimited).', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Count of successful orders that used this coupon.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('applicability', models.CharField(choices=[('WHOLE_ORDER', 'Whole Order'), ('CATEGORY', 'Selected Categories'), ('MENU_ITEM', 'Selected Menu Items')], default='WHOLE_ORDER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='applicable_coupons', to='menu.category')),
                ('applicable_items', models.ManyToManyField(blank=True, related_name='applicable_coupons', to='menu.menuitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='restaurant.restaurant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='applied_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('restaurant', 'code'), name='unique_coupon_code_per_restaurant'),
        ),
    ]
