# Generated by Django 6.1 on 2026-09-20 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_coupon_code_snapshot_and_more'),
        ('restaurant', '0005_branch_remove_floor_unique_floor_name_per_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.branch'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='restaurant.branch'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_sessions', to='restaurant.branch'),
        ),
    ]
