# Generated by Django 6.1 on 2026-09-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_branch_paymenttransaction_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='settings_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
