# Generated by Django 6.1 on 2026-09-21 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def release_existing_settled_sessions(apps, schema_editor):
    TableSession = apps.get_model("orders", "TableSession")
    Table = apps.get_model("restaurant", "Table")
    alias = schema_editor.connection.alias
    now = timezone.now()
    cutoff = max(timezone.localtime(now).replace(hour=0, minute=0, second=0, microsecond=0),
                 now - timezone.timedelta(hours=12))
    sessions = TableSession.objects.using(alias)
    for session in sessions.filter(status="OPEN").iterator():
        orders = session.orders.using(alias).exclude(status="CANCELLED")
        if not orders.exists():
            continue
        if orders.exclude(status="COMPLETED").exclude(status="SERVED", payment_status="PAID").exists():
            continue
        sessions.filter(pk=session.pk).update(status="CLOSED", closed_at=now, clean_needed=True)
        if not sessions.filter(table_id=session.table_id, status="OPEN", opened_at__gte=cutoff).exists():
            Table.objects.using(alias).filter(pk=session.table_id).exclude(
                status__in=["RESERVED", "OUT_OF_SERVICE"],
            ).update(status="AVAILABLE")


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_backfill_receipt_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='clean_needed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='cleaned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='cleaned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaned_table_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(release_existing_settled_sessions, migrations.RunPython.noop),
    ]
